baseurl      = "localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Сайт портфолио с работами за весь период обучения в РГПУ имени А.И.Герцена"

  # Set a background for the homepage
  backgroundImage = "/images/background.jpg"

  defaultTheme = "light"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  

  # Metadata mostly used in document's head
  description = "Portfolio"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Мое портфолио"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]

    [languages.en.params.logo]
      logoText = "julia1gin"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "1 курс"
    name       = "1 курс"
    url        = "/first_course"
  [[menu.main]]
    identifier = "2 курс"
    name       = "2 курс"
    url        = "/second_course"
  [[menu.main]]
    identifier = "3 курс"
    name       = "3 курс"
    url        = "/third_course"
  [[menu.main]]
    identifier = "О себе"
    name       = "О себе"
    url        = "/about"